name: Unity Build (Windows)

on:
  workflow_dispatch: {}     # 수동 실행
  # push:
  #   branches: [ "main" ]  # 원하면 주석 해제

jobs:
  build:
    if: ${{ secrets.UNITY_LICENSE != '' }}   # 라이선스 없으면 스킵
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          targetPlatform: StandaloneWindows64
          allowDirtyBuild: true
          # unityVersion: auto  # 자동 감지 (ProjectSettings/ProjectVersion.txt)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: build/StandaloneWindows64
